source "https://supermarket.chef.io"

metadata

cookbook 'copyleft-base', path: '../copyleft-base'
cookbook 'copyleft-java', path: '../copyleft-java'
cookbook 'copyleft-tomcat', path: '../copyleft-tomcat'
cookbook 'copyleft-postgres', path: '../copyleft-postgres'
