name             'copyleft-base'
maintainer       'Hobbyists at Copyleft.io'
maintainer_email 'brian.hooper@copyleft.io'
license          'GNU General Public License 3.0'
description      'Installs/Configures Base Ubuntu 16.04 Instance'
long_description 'Installs/Configures Base Ubuntu 16.04 Instance for the Hobbyists at Copyleft.io'
version          '1.0.0'

depends 'chef-client'
depends 'apt'
