---
driver:
  name: vagrant
  network:
    # Elastic Search Port
    - ["forwarded_port", {guest: 9200, host: 9200, auto_correct: true}]
    # Kibana Native Port
    - ["forwarded_port", {guest: 5600, host: 5600, auto_correct: true}]
    # Logstash Port
    - ["forwarded_port", {guest: 5044, host: 5044, auto_correct: true}]
    # nginx Proxy for Kibana
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  customize:
    natdnshostresolver1: "on"

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  # - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[copyleft-elkstack::default]
    attributes:
