name 'copyleft-elkstack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures copyleft-elkstack'
long_description 'Installs/Configures copyleft-elkstack'
version '0.1.0'

depends 'yum'
depends 'chef-client'
