---
driver:
  name: vagrant
  require_chef_omnibus: 12.12.13
  customize:
    memory: 2048
  network:
    - ["private_network", {ip: "192.168.168.168", auto_config: false}]
    - ["forwarded_port", {guest: 3000, host: 3000}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[copyleft-base::default]
      - recipe[copyleft-sensu::default]
    attributes:
