name 'copyleft-sensu'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures copyleft-sensu'
long_description 'Installs/Configures copyleft-sensu'
version '0.1.0'
