---
driver:
  name: vagrant
  customize:
    memory: 2048
  network:
    - ["private_network", {ip: "192.168.168.168"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[copyleft-base::default]
      - recipe[copyleft-docker::install]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      docker:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
