name             'copyleft-jumpcloud'
maintainer       'Hobbyists at Copyleft.io'
maintainer_email 'brian.hooper@copyleft.io'
license          'GNU General Public License 3.0'
description      'Installs/Configures copyleft-jumpcloud'
long_description 'Installs/Configures copyleft-jumpcloud'
version          '1.0.0'
